export const translateVar = {
	RU: {
		1:'Язык',
		2:'Тема',
		3:'Админ панель',
		4:'Войти',
		5:'Локация',
		6:'Новости',
		7:'Свяжитесь с нами',
		8:'Найдите идеальное место для вашей семьи',
		9:'Покупка дома - это событие, меняющее жизнь, поэтому разве ваш агент по недвижимости не должен быть тем, кто меняет жизнь.',
		10:'Купить',
		11:'Арендовать',
		12:'Продать',
		13:'Местоположение',
		14:'Дакка',
		15:'Катманду',
		16:'Калькутта',
		17:'Мумбаи',
		18:'Тип недвижимости',
		19:'Дуплекс',
		20:'Таунхаус',
		21:'Квартира',
		22:'Квартира',
		23:'Цена',
		24:'Поиск',
		25:'Местоположение',
		26:'Дакка',
		27:'Катманду',
		28:'Калькутта',
		29:'Мумбаи',
		30:'Тип недвижимости',
		31:'Дуплекс',
		32:'Таунхаус',
		33:'Квартира',
		34:'Квартира',
		35:'Цена',
		36:'$4000-$8000',
		37:'$8000-$10000',
		38:'$10000-$16000',
		39:'$16000-$20000',
		40:'Поиск',
		41:'Местоположение',
		42:'Дакка',
		43:'Катманду',
		44:'Калькутта',
		45:'Мумбаи',
		46:'Тип недвижимости',
		47:'Дуплекс',
		48:'Таунхаус',
		49:'Квартира',
		50:'Квартира',
		51:'Цена',
		52:'Поиск',
		53:'Наши партнеры',
		54:'Популярная недвижимость',
		55:'ПОСМОТРЕТЬ ВСЕ',
		56:'Резиденция на Капитолийском холме',
		57:'Просмотреть подробности',
		58:'Picket Fence Realty',
		59:'Восточный Лондон',
		60:'Просмотреть подробности',
		61:'Banyon Tree Realty',
		62:'Восточный Лондон',
		63:'Просмотреть подробности',
		64:'Corsair Real Estate',
		65:'Восточный Лондон',
		66:'Просмотреть подробности',
		67:'Sequoia Real Estate',
		68:'Восточный Лондон',
		69:'Просмотреть подробности',
		70:'Strive Partners Realty',
		71:'Восточный Лондон',
		72:'Просмотреть подробности',
		73:'Рекомендуемая недвижимость',
		74:'Недвижимость - это переполненная сфера. Но с ростом числа покупателей, приобретающих дома через агентов по недвижимости и брокеров, появляется множество ',
		75:'100% Безопасность',
		76:'Для многих из нас покупка дома - это мечта, и ее нелегко осуществить.',
		77:'Бесплатный кондиционер',
		78:'Для многих из нас покупка дома - это мечта, и ее нелегко осуществить.',
		79:'Цветочный сад',
		80:'Для многих из нас покупка дома - это мечта, и ее нелегко осуществить.',
		81:'Парковщики и грузчики',
		82:'Для многих из нас покупка дома - это мечта, и ее нелегко осуществить.',
		83:'Мебель в аренду',
		84:'Мебель в аренду',
		85:'Бассейн',
		86:'Для многих из нас покупка дома - это мечта, и ее нелегко осуществить.',
		87:'Отзывы',
		88:'Наши ценные клиенты говорят',
		89:'Джастин Ли',
		90:'Продуктовый дизайнер в Ito',
		91:'Хороший агент по недвижимости не исчезает после подписания заключительного контракта. Покупка большего дома не обязательно означает трату больших денег. Прошел через это. Сделал это. Продал. Купил. Объединил все вместе.',
		92:'Ангел Кейт',
		93:'Продуктовый дизайнер в Ito',
		94:'Хороший агент по недвижимости не исчезает после подписания заключительного контракта. Покупка большего дома не обязательно означает трату больших денег. Прошел через это. Сделал это. Продал. Купил. Объединил все вместе.',
		95:'Джесси Пинкман',
		96:'Продуктовый дизайнер в Ito',
		97:'Хороший агент по недвижимости не исчезает после подписания заключительного контракта. Покупка большего дома не обязательно означает трату больших денег. Прошел через это. Сделал это. Продал. Купил. Объединил все вместе.',
		98:'Уолтер Уайт',
		99:'Продуктовый дизайнер в Ito',
		100:'Хороший агент по недвижимости не исчезает после подписания заключительного контракта. Покупка большего дома не обязательно означает трату больших денег. Прошел через это. Сделал это. Продал. Купил. Объединил все вместе.',
		101:'Получите список вашего дома как владелец',
		102:'Вот список величайших слоганов компаний по недвижимости всех времен. Эти запоминающиеся слоганы следуют за величайшей недвижимостью.',
		103:'Подписаться',
		104:'Вопреки распространенному мнению, Lorem Ipsum - это не просто случайный текст. У него есть',
		105:'О нас',
		106:'Компания',
		107:'Команда',
		108:'Карьера',
		109:'Блоги',
		110:'Продукты',
		111:'Электронные книги',
		112:'Презентации',
		113:'Управление',
		114:'Панель управления',
		115:'Адрес',
		116:'Доставка по стране',
		117:'Пост на пляже',
		118:'Главная',
		119:'Свойства',
		120:'О нас',
		121:'Блог',
		122:"Выйти"
	},
	EN: {
		1:'Language',
		2:'Theme',
		3:'Admin Panel',
		4:'Login',
		5:'Location',
		6:'News',
		7:'Contact us',
		8:'Find the perfect place to stay with your family',
		9:'Buying a home is a life-changing experience, so shouldn’t your real estate agent be a life changer.',
		10:'Buy',
		11:'Rent',
		12:'Sell',
		13:'Location',
		14:'Dhaka',
		15:'Kathmandu',
		16:'Calcutta',
		17:'Mumbai',
		18:'Property type',
		19:'Duplex',
		20:'Townhouse',
		21:'Apartment',
		22:'Flat',
		23:'Price',
		24:'Search',
		25:'Location',
		26:'Dhaka',
		27:'Kathmandu',
		28:'Calcutta',
		29:'Mumbai',
		30:'Property type',
		31:'Duplex',
		32:'Townhouse',
		33:'Apartment',
		34:'Flat',
		35:'Price',
		36:'$4000-$8000',
		37:'$8000-$10000',
		38:'$10000-$16000',
		39:'$16000-$20000',
		40:'Search',
		41:'Location',
		42:'Dhaka',
		43:'Kathmandu',
		44:'Calcutta',
		45:'Mumbai',
		46:'Property type',
		47:'Duplex',
		48:'Townhouse',
		49:'Apartment',
		50:'Flat',
		51:'Price',
		52:'Search',
		53:'Our Partners',
		54:'Popular Properties',
		55:'VIEW ALL',
		56:'Capital hill residence',
		57:'View Details',
		58:'Picket Fence Realty',
		59:'East London',
		60:'View Details',
		61:'Banyon Tree Realty',
		62:'East London',
		63:'View Details',
		64:'Corsair Real Estate',
		65:'East London',
		66:'View Details',
		67:'Sequoia Real Estate',
		68:'East London',
		69:'View Details',
		70:'Strive Partners Realty',
		71:'East London',
		72:'View Details',
		73:'Property Featured',
		74:'Real estate is a crowded field. But with the number of buyers purchasing homes through real estate agents and brokers growing there’s plenty of ',
		75:'100% Security',
		76:'For many of us, buying a home is a dre and one not easily attainable.',
		77:'Free air conditioner',
		78:'For many of us, buying a home is a dre and one not easily attainable.',
		79:'Flower garden',
		80:'For many of us, buying a home is a dre and one not easily attainable.',
		81:'Parkers & movers',
		82:'For many of us, buying a home is a dre and one not easily attainable.',
		83:'Rental furniture',
		84:'Rental furniture',
		85:'Swimming pool',
		86:'For many of us, buying a home is a dre and one not easily attainable.',
		87:'Reviews',
		88:'Our valuable customer says',
		89:'Justin Lee',
		90:'Products Designer at Ito',
		91:'A good real estate agent doesn’t disappear once the closing IN signed.Buying a bigger home doesn’t necessarily mean spendi more money.Been there. Done that. Sold. Bought Bringing It All Together.',
		92:'Angel Cathe',
		93:'Products Designer at Ito',
		94:'A good real estate agent doesn’t disappear once the closing IN signed.Buying a bigger home doesn’t necessarily mean spendi more money.Been there. Done that. Sold. Bought Bringing It All Together.',
		95:'Jessie Pinkman',
		96:'Products Designer at Ito',
		97:'A good real estate agent doesn’t disappear once the closing IN signed.Buying a bigger home doesn’t necessarily mean spendi more money.Been there. Done that. Sold. Bought Bringing It All Together.',
		98:'Walter White',
		99:'Products Designer at Ito',
		100:'A good real estate agent doesn’t disappear once the closing IN signed.Buying a bigger home doesn’t necessarily mean spendi more money.Been there. Done that. Sold. Bought Bringing It All Together.',
		101:'Get listed your home as  a owner',
		102:'Here is a list of the greatest real estate company slogans of all-time. These catchy slogans are followed by the Greatest Real Estate.',
		103:'Subscribe',
		104:'Contrary to popular  is not simply random text. It has',
		105:'About',
		106:'Company',
		107:'Team',
		108:'Career',
		109:'Blogs',
		110:'Products',
		111:'E-Books',
		112:'Presentations',
		113:'Management',
		114:'Dashboard',
		115:'Address',
		116:'Country Delevery',
		117:'Counter Beach Post',
		118:'Home',
		119:'Properties',
		120:'About Us',
		121:'Blog',
		122:'log out'
	}
}